# Generated by Django 4.1.7 on 2023-03-30 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='Sample',
            name='droll',
            field=models.CharField(default='hello', max_length=50),
        ),
        migrations.AddField(
            model_name='Sample',
            name='rating',
            field=models.FloatField(default=2.3),
        ),
        migrations.AddField(
            model_name='Sample',
            name='review',
            field=models.IntegerField(default=5),
        ),
    ]
